#!/usr/bin/env bash
pushd /etc/nixos

echo "Pull? (y/n default y)"
read -r input
if [ "$input" != "n" ]; then
  export do_pull=1
fi
echo "Update? (y/n default n)"
read -r input
if [ "$input" = "y" ]; then
  export do_update=1
fi
echo "Edit config? (y/n default y)"
read -r input
if [ "$input" != "n" ]; then
  export edit_cfg=1
fi
echo "Push changes? (y/n default y)"
read -r input
if [ "$input" != "n" ]; then
  export do_push=1
fi

if [ "$do_pull" = "1" ]; then
  git pull
fi

if [ "$edit_cfg" = "1" ]; then
  nvim .
fi

if [ "$do_update" = "1" ]; then
  nix flake update
fi

pkexec nh os switch /etc/nixos -R

if [ $? -ne 0 ]; then
  popd
  zenity --info --text="Nixos Rebuild Failed 💔💔💔"
  echo "Nixos Rebuilt Unsuccessful, see above"
  read
  exit 1
fi

echo "Rebuild success!"

if [ "$do_push" = "1" ]; then
  current=$(nixos-rebuild list-generations | grep current)
  git add .
  git commit -a -m "$current"
  git push
fi

popd # return to whatever dir you were in

zenity --info --text="Nix Rebuild Ok 🤠"
