[shell]
niri_overview_type_to_launch_enabled = true

[theme]
builtin = "Tokyo-Night"

# widgets

[widget.control-center]
enabled = false

[widget.media]
hide_when_no_media = true

[widget.wallpaper]
enabled = false

[widget.clock]
format = "{:%b %d, %I:%M}"

# session options

[[shell.session.actions]]
action = "lock"
countdown_seconds = 0.0
enabled = true
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 0.0
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
countdown_seconds = 0.0
enabled = true
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 0.0
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 0.0
enabled = true
shortcut = "5"
variant = "destructive"

[[shell.session.actions]]
action = "command"
command = "systemctl reboot --boot-loader-entry=auto-windows"
countdown_seconds = 5.0
enabled = true
glyph = "brand-windows-filled"
label = "Windows"
shortcut = "6"
variant = "default"