[shell]
niri_overview_type_to_launch_enabled = true

[theme]
builtin = "Tokyo-Night"

[widget.control-center]
enabled = false

[widget.media]
hide_when_no_media = true

[widget.wallpaper]
enabled = false

[widget.clock]
format = "{:%b %d, %I:%M}"